# A short, descriptive name of this building block collection
name: 3D Demo of ICSM 3DCSDM for WA

# Short abstract for this collection (optional)
abstract: |
  This is an example showing the potential for the WA profile of the ICSM Cadastre Survey Model to be extended to full 3D 

# Description for this collection (optional)
description: |
  It extends the topo-feature base to support Polyhedron objects and constrains the WA-Profile to force use of these for parcels of certain types.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: surround.demo.3dcadastre

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://icsm-au.github.io/3d-csdm-profile-wa/build/register.json
  - https://ogcincubator.github.io/topo-feature/build/register.json

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
