"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Example of a sinmple GeoJSON Feature specialisation'
$defs:
  MyFeature:
    allOf:
      - $ref: bblocks://ogc.geo.features.feature
      - properties:
          properties:
            $ref: ../mySchema/schema.yaml
anyOf:
  - $ref: "#/$defs/MyFeature"
